#!/usr/bin/env bash

# Change directory to the directory of the script
cd "$(dirname "$0")"

# Abort on error
set -e


# Display logo
echo -e "\n\033[38;5;255m\033[48;5;234m\033[1m                         \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m        Jumpstart        \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m     by Aditya Pillai    \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m                         \033[0m\n"

# Display LICENSE
echo "Copyright (C) 2018 Aditya Pillai"
echo "This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE."
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions; see LICENSE for details."; echo;

# Ensure user has read the LICENSE
read -p "By continuing, you agree to the terms above. Press [enter] to continue..."; echo;

# DEPRECATED:
# echo "The script will now execute sudo -v so that you will not need to type in your password again during the execution of this script..."; echo;
# Require sudo password
# sudo -v

# Show what must be installed to run the program
echo "The script will now install three necessary prerequisites -- Xcode Command Line Tools, Homebrew, and Python..."; echo;

# Ensure the user understands what must be installed.
read -p "Press [enter] to continue..."; echo;

# Install Xcode Command Line Tools
echo "Ensuring Xcode Command Line Tools are installed..."; echo;
./scripts/xcode-clt.sh 

# Install Homebrew
./scripts/homebrew.sh

# Install Python3
./scripts/python.sh

# Create a virtual environment
./scripts/venv.sh

echo "Activating virtual environment..."; echo;
source .venv/bin/activate

echo "Installing requirements..."; echo;
pip install -r requirements.txt &> /dev/null

echo "The prerequisites are now installed... Press [enter] to continue the installation..."; read

read -r -p "Do you wish to customize your installation? [yes]: " confirm
  case "$confirm" in
    no) echo; echo "Installing defaults specified in ./global_vars/vars.yml"
        ;;
      
     *) echo; echo "Confirmed. Customizing installation...";
         echo; ansible-playbook playbooks/configure.yml -i inventories/inventory
        ;;
  esac

echo
read -r -p "Installation is ready to begin. Press [enter] to start the automated process... " a

# Run ansible playbook
ansible-playbook -i inventories/inventory playbooks/main.yml --extra-vars "@./global_vars/vars.yml" --ask-become-pass
