#!/usr/bin/env bash

# Change directory to the directory of the script
cd "$(dirname "$0")"

set -e



echo -e "\n\033[38;5;255m\033[48;5;234m\033[1m                         \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m        Jumpstart        \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m     by Aditya Pillai    \033[0m"
echo -e "\033[38;5;255m\033[48;5;234m\033[1m                         \033[0m\n"

echo "Copyright (C) 2018 Aditya Pillai"
echo "This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE."
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions; see LICENSE for details."; echo;


# ./util/venv.sh
echo; echo "Activating virtual environment..."
source .venv/bin/activate

echo; echo "Installing requirements..."
pip install -r requirements.txt

echo;
read -r -p "Do you wish to customize your installation? [yes]: " confirm
  case "$confirm" in
    no) echo; echo "Installing defaults specified in ./global_vars/vars.yml";;
     *) echo; echo "Confirmed. Customizing installation.";
         echo; ansible-playbook playbooks/configure.yml -i inventories/inventory
  esac

echo
read -r -p "Installation is ready to begin. Press [enter] to start the automated process... " a

# Run ansible playbook
ansible-playbook -i inventories/inventory playbooks/main.yml --extra-vars "@./global_vars/vars.yml"